### PR TITLE
4 create an onboarding screen

### PR DESCRIPTION
**Pull request by dennism501**
1. Created a new assets folder for the images
2. Added the Onboarding screen. 
3. Not added the discussed folder structure in #4

### CODE REVIEW

**Review by OlivierJM — APPROVED** [review]
Looks great, I am still trying to resolve #11, once that is done most work will be smoother but in the meantime other issues can be moving.

**Comment by dennism501** [comment]
@OlivierJM does this PR need to be closed?

**Comment by OlivierJM** [comment]
Not yet, I will merge it soon.

**Comment by dennism501** [comment]
Okay cool

**Pull request merged**
