### PR TITLE
Fixed wrong file extension reference from .png to .svg in the assets …

### PR DESCRIPTION
**Pull request by ikayz**
Change .png to .svg file reference in assets folder for the file being used in Onboarding.js

### CODE REVIEW

**Review by OlivierJM — APPROVED** [review]

**Comment by OlivierJM** [comment]
@ikayz try did tests pass after making this change ?

**Comment by OlivierJM** [comment]
You can try it with changes in here #14

**Comment by ikayz** [comment]
> @ikayz try did tests pass after making this change ?

Yes, before the change when I pulled from upstream. I was getting errors when I tried running the app in an emulator until I looked for what was causing it. Then I changed that same line and it started working.

**Comment by OlivierJM** [comment]
> > @ikayz try did tests pass after making this change ?
> 
> Yes, before the change when I pulled from upstream. I was getting errors when I tried running the app in an emulator until I looked for what was causing it. Then I changed that same line and it started working.

That sounds great!! we will rebase with #14 and see what happens, in the meantime I will merge this into master.

**Pull request merged**
