### PR TITLE
🚧 Updated readme with a basic structure we can work on

### PR DESCRIPTION
**Pull request by YoramGondwe**
This PR is just to establish a structure for the README.md I will make more updates as information is made available

### CODE REVIEW

**Comment by OlivierJM** [comment]
this looks good @YoramGondwe

**Review by OlivierJM — APPROVED** [review]
lgtm

**Comment by YoramGondwe** [comment]
> lgtm

What do you mean by lgtm?

**Comment by OlivierJM** [comment]
> > lgtm
> 
> What do you mean by lgtm?

It looks good to me 
[ref](https://www.freecodecamp.org/news/what-do-cryptic-github-comments-mean-9c1912bcc0a4/)

**Pull request merged**
